export const ProfileActionTypes = {
  LISTEN_TO_CURRENT_USER_PROFILE: 'LISTEN_TO_CURRENT_USER_PROFILE',
  LISTEN_TO_SELECTED_USER_PROFILE: 'LISTEN_TO_SELECTED_USER_PROFILE',
  LISTEN_TO_USER_PHOTOS: 'LISTEN_TO_USER_PHOTOS',
  LISTEN_TO_USER_EVENTS: 'LISTEN_TO_USER_EVENTS',
  LISTEN_TO_FOLLOWERS: 'LISTEN_TO_FOLLOWERS',
  LISTEN_TO_FOLLOWINGS: 'LISTEN_TO_FOLLOWINGS',
  SET_FOLLOW_USER: 'SET_FOLLOW_USER',
  SET_UNFOLLOW_USER: 'SET_UNFOLLOW_USER',
  CLEAR_FOLLOWINGS: 'CLEAR_FOLLOWINGS',
};
