export const EventActionTypes = {
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  FETCH_EVENTS: 'FETCH_EVENTS',
  LISTEN_TO_EVENT_CHAT: 'LISTEN_TO_EVENT_CHAT',
  CLEAR_COMMENTS: 'CLEAR_COMMENTS',
  LISTEN_TO_SELECTED_EVENT: 'LISTEN_TO_SELECTED_EVENT',
  CLEAR_EVENTS: 'CLEAR_EVENTS',
};
